export function getDefaultInitiatives() {
  return [
    { slug: "cerebro-robotico-educativo", name: "Cerebro robótico educativo", category: "ia_robotica" as const, status: "vision" as const, safetyScope: "Simulación y tutoría; sin movimiento autónomo", objective: "Diseñar un asistente conversacional multimodal que enseñe idiomas y capacidades técnicas mediante interacción guiada.", nextMilestone: "Definir perfiles de aprendizaje, límites de evaluación y prototipo conversacional." },
    { slug: "cultivo-autonomo", name: "Cultivo autónomo y resiliente", category: "agrotech" as const, status: "prototipo" as const, safetyScope: "LabOS en simulación; control físico deshabilitado", objective: "Desarrollar un sistema de cultivo supervisado con gemelo digital, telemetría y planes de riego o nutrientes evaluados por personas.", nextMilestone: "Conectar una fuente de telemetría de solo lectura y validar el modelo con mediciones reales." },
    { slug: "cocina-automatizada", name: "Cocina automatizada multicultural", category: "food_automation" as const, status: "vision" as const, safetyScope: "Diseño digital y análisis de procesos; sin manipulación térmica", objective: "Modelar una estación que planifique recetas, ingredientes y flujos de preparación adaptados a culturas, gustos y restricciones alimentarias.", nextMilestone: "Crear el gemelo digital del flujo de receta y el inventario de ingredientes." },
    { slug: "tecnologia-asistiva", name: "Tecnología asistiva para autonomía", category: "assistive_tech" as const, status: "vision" as const, safetyScope: "Investigación centrada en la persona; revisión clínica obligatoria", objective: "Explorar ayudas para movilidad, alimentación y rutinas de cuidado, incluyendo camas, sillas y sistemas de asistencia.", nextMilestone: "Definir necesidades con especialistas, cuidadores y usuarios antes de cualquier prototipo físico." },
    { slug: "automata-limpieza", name: "Autómata de limpieza doméstica", category: "cleaning_automation" as const, status: "vision" as const, safetyScope: "Gemelo digital y tareas simuladas; sin movimiento, químicos ni manipulación física", objective: "Modelar flujos de lavado de vajilla, limpieza de áreas, gestión de residuos, reciclaje y mantenimiento doméstico con prioridades y supervisión humana.", nextMilestone: "Definir zonas, materiales, riesgos de superficies y reglas de separación de residuos antes de cualquier prototipo físico." },
  ];
}
