import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { trpc } from "@/lib/trpc";
import { Bell, CheckCheck, CircleAlert, Info, Loader2, Radar } from "lucide-react";
import { toast } from "sonner";

const icons = { info: Info, atencion: CircleAlert, critico: CircleAlert };

export function NotificationsCenter({ notifications }: { notifications?: any[] }) {
  const utils = trpc.useUtils();
  const markRead = trpc.lab.markNotificationsRead.useMutation({ onSuccess: () => { utils.lab.dashboard.invalidate(); }, onError: (error) => toast.error(error.message) });
  const items = notifications ?? [];
  const unread = items.filter((item) => item.unread).length;
  return <Popover><PopoverTrigger asChild><Button variant="outline" size="icon" className="relative border-cyan-300/15 bg-cyan-300/[0.04] text-cyan-100 hover:bg-cyan-300/10 hover:text-cyan-50"><Bell className="size-4" />{unread ? <span className="absolute -right-1 -top-1 grid size-4 place-items-center rounded-full bg-cyan-300 text-[9px] font-bold text-slate-950">{unread > 9 ? "9+" : unread}</span> : null}</Button></PopoverTrigger><PopoverContent align="end" className="w-[360px] border-cyan-300/15 bg-[#09121d] p-0 text-slate-100"><div className="flex items-center justify-between border-b border-white/5 px-4 py-3"><div><p className="text-sm font-medium">Centro de notificaciones</p><p className="mt-0.5 text-[10px] uppercase tracking-[0.14em] text-slate-500">{unread ? `${unread} sin leer` : "Todo al día"}</p></div><Button variant="ghost" size="sm" disabled={!unread || markRead.isPending} onClick={() => markRead.mutate()} className="h-8 text-xs text-cyan-100 hover:bg-cyan-300/10 hover:text-cyan-50">{markRead.isPending ? <Loader2 className="mr-1.5 size-3.5 animate-spin" /> : <CheckCheck className="mr-1.5 size-3.5" />}Marcar leídas</Button></div><div className="max-h-[380px] overflow-y-auto p-2">{items.length ? items.map((item) => { const Icon = icons[item.severity as keyof typeof icons] ?? Radar; return <button type="button" key={item.id} onClick={() => item.unread && markRead.mutate({ notificationIds: [item.id] })} className={`w-full rounded-xl p-3 text-left transition-colors ${item.unread ? "bg-cyan-300/[0.045] hover:bg-cyan-300/[0.08]" : "hover:bg-white/[0.035]"}`}><div className="flex gap-3"><div className={`mt-0.5 grid size-8 shrink-0 place-items-center rounded-lg border ${item.severity === "critico" ? "border-rose-300/20 bg-rose-300/[0.05] text-rose-200" : item.severity === "atencion" ? "border-amber-300/20 bg-amber-300/[0.05] text-amber-100" : "border-cyan-300/15 bg-cyan-300/[0.04] text-cyan-100"}`}><Icon className="size-4" /></div><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-3"><p className="text-xs font-medium text-slate-200">{item.title}</p>{item.unread ? <span className="mt-1.5 size-1.5 shrink-0 rounded-full bg-cyan-300" /> : null}</div><p className="mt-1 text-xs leading-5 text-slate-500">{item.detail}</p><p className="mt-2 text-[10px] text-slate-600">{new Date(item.createdAt).toLocaleString()}</p></div></div></button>; }) : <div className="p-8 text-center text-sm text-slate-500">No hay notificaciones todavía.</div>}</div><div className="border-t border-white/5 px-4 py-2.5"><p className="text-[10px] text-slate-600">Las notificaciones reflejan datos recibidos y eventos auditables; no generan control físico.</p></div></PopoverContent></Popover>;
}
