import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { CloudUpload, Loader2, Mic, Square, WandSparkles } from "lucide-react";
import { useRef, useState } from "react";
import { toast } from "sonner";

function toBase64(blob: Blob) { return new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result).split(",")[1] ?? ""); reader.onerror = () => reject(reader.error); reader.readAsDataURL(blob); }); }

export function VoiceServiceRecorder({ profiles, providers }: { profiles: any[]; providers: any[] }) {
  const utils = trpc.useUtils(); const provider = providers[0]; const [profileId, setProfileId] = useState(profiles.find((item) => item.privacyAcknowledged) ? String(profiles.find((item) => item.privacyAcknowledged).id) : "none"); const [promptText, setPromptText] = useState("Lee una frase breve para practicar pronunciación."); const [recording, setRecording] = useState(false); const chunks = useRef<Blob[]>([]); const recorder = useRef<MediaRecorder | null>(null);
  const transcribe = trpc.lab.transcribeVoiceAudio.useMutation({ onError: (error) => toast.error(error.message) }); const save = trpc.lab.saveVoicePractice.useMutation({ onSuccess: () => { toast.success("Audio transcrito y práctica guardada."); utils.lab.dashboard.invalidate(); }, onError: (error) => toast.error(error.message) });
  const start = async () => { if (!navigator.mediaDevices?.getUserMedia || !window.MediaRecorder) { toast.error("La grabación no está disponible en este navegador. Usa el reconocimiento local o escribe la respuesta."); return; } try { const stream = await navigator.mediaDevices.getUserMedia({ audio: true }); const mediaRecorder = new MediaRecorder(stream, { mimeType: MediaRecorder.isTypeSupported("audio/webm") ? "audio/webm" : undefined }); chunks.current = []; mediaRecorder.ondataavailable = (event) => { if (event.data.size) chunks.current.push(event.data); }; mediaRecorder.onstop = async () => { stream.getTracks().forEach((track) => track.stop()); const blob = new Blob(chunks.current, { type: mediaRecorder.mimeType || "audio/webm" }); try { const audioBase64 = await toBase64(blob); const transcript = await transcribe.mutateAsync({ profileId: Number(profileId), promptText, audioBase64, mimeType: blob.type || "audio/webm" }); await save.mutateAsync({ profileId: Number(profileId), promptText, transcript: transcript.transcript, detectedLanguage: transcript.detectedLanguage ?? undefined, audioStorageKey: transcript.audioStorageKey, audioUrl: transcript.audioUrl }); } catch { /* las mutaciones comunican los errores */ } }; recorder.current = mediaRecorder; mediaRecorder.start(); setRecording(true); } catch { toast.error("No se concedió permiso de micrófono. Puedes usar el reconocimiento local o escribir la respuesta."); } };
  const stop = () => { recorder.current?.stop(); recorder.current = null; setRecording(false); };
  return <section className="rounded-2xl border border-violet-300/15 bg-violet-300/[0.025] p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-violet-200">Transcripción segura · {provider?.provider ?? "Proveedor pendiente"}</p><h3 className="mt-1 font-display text-lg text-slate-100">Grabación y transcripción por servicio</h3><p className="mt-2 max-w-2xl text-xs leading-5 text-slate-500">Con consentimiento, el audio se guarda temporalmente en almacenamiento seguro y se procesa por el servicio configurado. El resultado se conserva como práctica; no activa hardware ni comparte comandos.</p></div><WandSparkles className="size-5 text-violet-200" /></div><div className="mt-5 grid gap-3 md:grid-cols-[1fr_1.4fr_auto]"><div><Label className="text-xs text-slate-400">Perfil autorizado</Label><Select value={profileId} onValueChange={setProfileId}><SelectTrigger className="mt-2"><SelectValue /></SelectTrigger><SelectContent>{profiles.filter((item) => item.privacyAcknowledged).map((item) => <SelectItem key={item.id} value={String(item.id)}>{item.displayName}</SelectItem>)}<SelectItem value="none" disabled>Selecciona un perfil con consentimiento</SelectItem></SelectContent></Select></div><div><Label className="text-xs text-slate-400">Consigna de transcripción</Label><Textarea className="mt-2 min-h-10" value={promptText} onChange={(event) => setPromptText(event.target.value)} /></div><div className="flex items-end">{recording ? <Button onClick={stop} className="w-full bg-rose-300 text-slate-950 hover:bg-rose-200"><Square className="mr-2 size-4" />Detener y transcribir</Button> : <Button disabled={profileId === "none" || !provider?.enabled || transcribe.isPending || save.isPending} onClick={start} className="w-full bg-violet-300 text-slate-950 hover:bg-violet-200">{transcribe.isPending || save.isPending ? <Loader2 className="mr-2 size-4 animate-spin" /> : <Mic className="mr-2 size-4" />}Grabar</Button>}</div></div><p className="mt-4 flex items-start gap-2 text-[11px] leading-5 text-slate-600"><CloudUpload className="mt-0.5 size-3.5 shrink-0 text-violet-200" />Referencia de servicio: {provider?.endpointPlaceholder ?? "por definir"} · Límite de audio: {provider?.maxAudioMb ?? 16} MB. Los perfiles sin consentimiento no aparecen como destinos de transcripción.</p></section>;
}
